
global.Config = {
    port: 3000,
    itemPickupDistance: 2.0,
    blockPlaceDistance: 96, //Pixels
    tickDuration: 1000 / 60,
    fakeLag: 0,
    fakeJitter: 0,
    respawnTime: 1,
    textures: [
        "healthbar.png",
        "feet.png",
        "tool.png",
        "body.png",
        "head.png",
        "rightArm.png",
        "leftArm.png",
        "monster/feet.png",
        "monster/head.png",
        "monster/rightArm.png",
        "monster/leftArm.png",
        "turret/bottom.png",
        "ghost.png",
        "shovelAtlas.png",
        "swordAtlas.png",
        "gunAtlas.png",
        "itemAtlas.png",
        "hatAtlas.png",
        "blockAtlas.png",
        "blockPosGood.png",
        "blockPosBad.png",
        "egg.png",
        "bigEgg.png",
        "dynamite.png"
    ],
}
